// <auto-generated />
using System;
using EventTicketing.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventTicketing.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429150903_AddEventTypeAndTimes")]
    partial class AddEventTypeAndTimes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("EventTicketing.Api.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedNumber")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("EventTicketing.Api.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableSeats")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 48,
                            Description = "An intimate evening of live jazz featuring the city's finest musicians. Expect smooth bebop, cool jazz, and soulful improvisation.",
                            EndTime = new DateTime(2026, 5, 2, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Music",
                            ImageUrl = "https://images.unsplash.com/photo-1548163111-bc419d75fef4?w=800&q=80",
                            Price = 25.00m,
                            StartTime = new DateTime(2026, 5, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jazz Night",
                            TotalSeats = 120,
                            Venue = "Blue Note Club"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 212,
                            Description = "A full-day conference on modern software development — AI, distributed systems, DevOps and beyond. Keynotes from industry leaders.",
                            EndTime = new DateTime(2026, 5, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Tech",
                            ImageUrl = "https://images.unsplash.com/photo-1582192730841-2a682d7375f9?w=800&q=80",
                            Price = 149.00m,
                            StartTime = new DateTime(2026, 5, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tech Conference 2026",
                            TotalSeats = 500,
                            Venue = "City Convention Centre"
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 134,
                            Description = "Stand-up comedy night featuring five rising comedians. Uncensored, hilarious, and perfect for a night out.",
                            EndTime = new DateTime(2026, 5, 7, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Comedy",
                            ImageUrl = "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800&q=80",
                            Price = 18.00m,
                            StartTime = new DateTime(2026, 5, 7, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Comedy Showcase",
                            TotalSeats = 200,
                            Venue = "Laugh Factory"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 870,
                            Description = "Conference finals — top two city teams battle for the championship. High energy, packed arena, one winner.",
                            EndTime = new DateTime(2026, 5, 9, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Sports",
                            ImageUrl = "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80",
                            Price = 45.00m,
                            StartTime = new DateTime(2026, 5, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Championship Basketball",
                            TotalSeats = 3000,
                            Venue = "City Arena"
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 91,
                            Description = "A full-day gathering for founders, investors, and innovators. Panels on fundraising, product-market fit, and scaling.",
                            EndTime = new DateTime(2026, 5, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Business",
                            ImageUrl = "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&q=80",
                            Price = 199.00m,
                            StartTime = new DateTime(2026, 5, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Startup Summit",
                            TotalSeats = 300,
                            Venue = "Grand Ballroom"
                        },
                        new
                        {
                            Id = 6,
                            AvailableSeats = 155,
                            Description = "A spectacular evening of Broadway's greatest hits performed by a cast of West End and Broadway veterans.",
                            EndTime = new DateTime(2026, 5, 14, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Theater",
                            ImageUrl = "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800&q=80",
                            Price = 85.00m,
                            StartTime = new DateTime(2026, 5, 14, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Broadway Hits Gala",
                            TotalSeats = 400,
                            Venue = "Empire Theatre"
                        },
                        new
                        {
                            Id = 7,
                            AvailableSeats = 623,
                            Description = "Over 50 local restaurants and wineries in one place. Tastings, live cooking demos, and expert-led wine pairings.",
                            EndTime = new DateTime(2026, 5, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Food",
                            ImageUrl = "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
                            Price = 35.00m,
                            StartTime = new DateTime(2026, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Food & Wine Festival",
                            TotalSeats = 1000,
                            Venue = "Riverside Park"
                        },
                        new
                        {
                            Id = 8,
                            AvailableSeats = 388,
                            Description = "A curated showcase of contemporary works from 30 emerging artists. Sculpture, digital art, painting, and installation.",
                            EndTime = new DateTime(2026, 5, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Art",
                            ImageUrl = "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&q=80",
                            Price = 15.00m,
                            StartTime = new DateTime(2026, 5, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Modern Art Exhibition",
                            TotalSeats = 500,
                            Venue = "City Gallery"
                        },
                        new
                        {
                            Id = 9,
                            AvailableSeats = 2140,
                            Description = "An explosive night of classic rock anthems. Three tribute bands covering Led Zeppelin, Queen, and AC/DC back to back.",
                            EndTime = new DateTime(2026, 5, 20, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Music",
                            ImageUrl = "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
                            Price = 65.00m,
                            StartTime = new DateTime(2026, 5, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rock Legends Live",
                            TotalSeats = 5000,
                            Venue = "Civic Stadium"
                        },
                        new
                        {
                            Id = 10,
                            AvailableSeats = 1047,
                            Description = "Annual 42 km city marathon through iconic landmarks. Open to all levels with 5 km and 10 km fun-run categories.",
                            EndTime = new DateTime(2026, 5, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Sports",
                            ImageUrl = "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&q=80",
                            Price = 30.00m,
                            StartTime = new DateTime(2026, 5, 21, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Marathon City Run",
                            TotalSeats = 2000,
                            Venue = "City Park"
                        },
                        new
                        {
                            Id = 11,
                            AvailableSeats = 22,
                            Description = "Journey through Italy's finest wine regions. Six guided tastings paired with artisan charcuterie and cheese.",
                            EndTime = new DateTime(2026, 5, 24, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Food",
                            ImageUrl = "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
                            Price = 55.00m,
                            StartTime = new DateTime(2026, 5, 24, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Italian Wine Tasting",
                            TotalSeats = 80,
                            Venue = "Vineyard Lounge"
                        },
                        new
                        {
                            Id = 12,
                            AvailableSeats = 9,
                            Description = "Hands-on evening workshop covering lighting, composition, and post-processing. Bring your camera or use a loaner.",
                            EndTime = new DateTime(2026, 5, 24, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Art",
                            ImageUrl = "https://images.unsplash.com/photo-1452780212461-64df12a92440?w=800&q=80",
                            Price = 75.00m,
                            StartTime = new DateTime(2026, 5, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Photography Workshop",
                            TotalSeats = 30,
                            Venue = "Art Studio"
                        },
                        new
                        {
                            Id = 13,
                            AvailableSeats = 204,
                            Description = "The City Philharmonic performs Beethoven's 5th and Dvořák's New World Symphony in a grand evening concert.",
                            EndTime = new DateTime(2026, 5, 28, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Music",
                            ImageUrl = "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&q=80",
                            Price = 70.00m,
                            StartTime = new DateTime(2026, 5, 28, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Symphony Orchestra",
                            TotalSeats = 600,
                            Venue = "Concert Hall"
                        },
                        new
                        {
                            Id = 14,
                            AvailableSeats = 67,
                            Description = "The biggest comedy event of the month. Seven headliners, two hours of non-stop laughs, free drinks on arrival.",
                            EndTime = new DateTime(2026, 5, 28, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Comedy",
                            ImageUrl = "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800&q=80",
                            Price = 22.00m,
                            StartTime = new DateTime(2026, 5, 28, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "City Comedy Night",
                            TotalSeats = 200,
                            Venue = "Laugh House"
                        },
                        new
                        {
                            Id = 15,
                            AvailableSeats = 173,
                            Description = "A prestigious evening of classical and contemporary ballet performed by the National Dance Company.",
                            EndTime = new DateTime(2026, 5, 30, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Theater",
                            ImageUrl = "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800&q=80",
                            Price = 90.00m,
                            StartTime = new DateTime(2026, 5, 30, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ballet Gala",
                            TotalSeats = 350,
                            Venue = "City Theater"
                        },
                        new
                        {
                            Id = 16,
                            AvailableSeats = 1532,
                            Description = "70+ street food vendors from 30 countries. Flavours, music, and fun for the whole family.",
                            EndTime = new DateTime(2026, 6, 1, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Food",
                            ImageUrl = "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
                            Price = 10.00m,
                            StartTime = new DateTime(2026, 6, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Street Food Carnival",
                            TotalSeats = 2000,
                            Venue = "Central Square"
                        },
                        new
                        {
                            Id = 17,
                            AvailableSeats = 789,
                            Description = "City-wide tennis open tournament. Singles and doubles brackets for all skill levels. Spectator entry included.",
                            EndTime = new DateTime(2026, 6, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Sports",
                            ImageUrl = "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80",
                            Price = 40.00m,
                            StartTime = new DateTime(2026, 6, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tennis Open",
                            TotalSeats = 1500,
                            Venue = "Sports Complex"
                        },
                        new
                        {
                            Id = 18,
                            AvailableSeats = 118,
                            Description = "Festival-circuit award-winning indie films screened back to back with Q&A sessions with the directors.",
                            EndTime = new DateTime(2026, 6, 5, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Art",
                            ImageUrl = "https://images.unsplash.com/photo-1536924430914-91f9e2041b83?w=800&q=80",
                            Price = 22.00m,
                            StartTime = new DateTime(2026, 6, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Indie Film Screening",
                            TotalSeats = 200,
                            Venue = "Cinema House"
                        },
                        new
                        {
                            Id = 19,
                            AvailableSeats = 14,
                            Description = "Lazy Sunday brunch with live jazz quartet. Three-course brunch menu with bottomless mimosas included.",
                            EndTime = new DateTime(2026, 6, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Music",
                            ImageUrl = "https://images.unsplash.com/photo-1548163111-bc419d75fef4?w=800&q=80",
                            Price = 45.00m,
                            StartTime = new DateTime(2026, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jazz Brunch",
                            TotalSeats = 60,
                            Venue = "Rooftop Lounge"
                        },
                        new
                        {
                            Id = 20,
                            AvailableSeats = 11,
                            Description = "Intensive one-day bootcamp. Build and deploy a full-stack web app from scratch. Beginners welcome.",
                            EndTime = new DateTime(2026, 6, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Tech",
                            ImageUrl = "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
                            Price = 299.00m,
                            StartTime = new DateTime(2026, 6, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Web Dev Bootcamp",
                            TotalSeats = 40,
                            Venue = "Tech Hub"
                        },
                        new
                        {
                            Id = 21,
                            AvailableSeats = 201,
                            Description = "Four hours of non-stop stand-up comedy. 12 comedians, rotating every 20 minutes. Your cheeks will hurt.",
                            EndTime = new DateTime(2026, 6, 12, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Comedy",
                            ImageUrl = "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800&q=80",
                            Price = 28.00m,
                            StartTime = new DateTime(2026, 6, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Comedy Marathon",
                            TotalSeats = 300,
                            Venue = "Comedy Palace"
                        },
                        new
                        {
                            Id = 22,
                            AvailableSeats = 63,
                            Description = "Latin beats, professional instructors, and a packed dance floor. Beginners' crash course at 7pm before the social.",
                            EndTime = new DateTime(2026, 6, 13, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Music",
                            ImageUrl = "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800&q=80",
                            Price = 30.00m,
                            StartTime = new DateTime(2026, 6, 13, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Salsa Dance Night",
                            TotalSeats = 150,
                            Venue = "Latin Club"
                        },
                        new
                        {
                            Id = 23,
                            AvailableSeats = 88,
                            Description = "Deep dives into DeFi, Web3 infrastructure, and enterprise blockchain. Networking dinner included.",
                            EndTime = new DateTime(2026, 6, 14, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Business",
                            ImageUrl = "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80",
                            Price = 249.00m,
                            StartTime = new DateTime(2026, 6, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blockchain Summit",
                            TotalSeats = 200,
                            Venue = "Conference Center"
                        },
                        new
                        {
                            Id = 24,
                            AvailableSeats = 144,
                            Description = "Classic films under the stars. Bring a blanket, grab a cocktail from the bar, and enjoy cinema the way it was meant to be.",
                            EndTime = new DateTime(2026, 6, 15, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Art",
                            ImageUrl = "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80",
                            Price = 18.00m,
                            StartTime = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Outdoor Cinema Night",
                            TotalSeats = 200,
                            Venue = "Rooftop Garden"
                        },
                        new
                        {
                            Id = 25,
                            AvailableSeats = 322,
                            Description = "Pop-up art market showcasing 40 local artists. Original paintings, prints, ceramics, and live art demonstrations.",
                            EndTime = new DateTime(2026, 6, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Art",
                            ImageUrl = "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&q=80",
                            Price = 5.00m,
                            StartTime = new DateTime(2026, 6, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Evening Art Market",
                            TotalSeats = 500,
                            Venue = "Warehouse District"
                        },
                        new
                        {
                            Id = 26,
                            AvailableSeats = 3211,
                            Description = "The biggest outdoor music festival of the summer. Eight bands across two stages, food trucks, and fireworks finale.",
                            EndTime = new DateTime(2026, 6, 19, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Music",
                            ImageUrl = "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
                            Price = 85.00m,
                            StartTime = new DateTime(2026, 6, 19, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Summer Rock Fest",
                            TotalSeats = 8000,
                            Venue = "Lakeside Amphitheatre"
                        },
                        new
                        {
                            Id = 27,
                            AvailableSeats = 2455,
                            Description = "30 food trucks, craft beers, and live acoustic music. Vote for your favourite truck and win prizes.",
                            EndTime = new DateTime(2026, 6, 21, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Food",
                            ImageUrl = "https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?w=800&q=80",
                            Price = 8.00m,
                            StartTime = new DateTime(2026, 6, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Food Truck Rally",
                            TotalSeats = 3000,
                            Venue = "Waterfront Plaza"
                        },
                        new
                        {
                            Id = 28,
                            AvailableSeats = 198,
                            Description = "A modern retelling of Shakespeare's Hamlet set in a near-future dystopia. Critically acclaimed production.",
                            EndTime = new DateTime(2026, 6, 26, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Theater",
                            ImageUrl = "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800&q=80",
                            Price = 65.00m,
                            StartTime = new DateTime(2026, 6, 26, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Theater Night: Hamlet",
                            TotalSeats = 300,
                            Venue = "Civic Theatre"
                        },
                        new
                        {
                            Id = 29,
                            AvailableSeats = 567,
                            Description = "Al fresco jazz concert in the park. Bring a picnic, bring friends, and let the music carry the evening.",
                            EndTime = new DateTime(2026, 6, 28, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Music",
                            ImageUrl = "https://images.unsplash.com/photo-1548163111-bc419d75fef4?w=800&q=80",
                            Price = 35.00m,
                            StartTime = new DateTime(2026, 6, 28, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Summer Jazz Concert",
                            TotalSeats = 1000,
                            Venue = "Park Amphitheatre"
                        });
                });

            modelBuilder.Entity("EventTicketing.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EventTicketing.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventTicketing.Api.Models.Card", b =>
                {
                    b.HasOne("EventTicketing.Api.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventTicketing.Api.Models.Order", b =>
                {
                    b.HasOne("EventTicketing.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTicketing.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventTicketing.Api.Models.User", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
